### ISSUE TITLE
No such file or directory

### ISSUE THREAD

**Issue by lovejackey** [quickbreach/SMBetray#5]
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 801, in __bootstrap_inner
    self.run()
  File "/root/Desktop/tools/SMBetray/lib/ebcLib.py", line 391, in run
    self.listen()
  File "/root/Desktop/tools/SMBetray/lib/ebcLib.py", line 289, in listen
    self.openFirewall()
  File "/root/Desktop/tools/SMBetray/lib/ebcLib.py", line 208, in openFirewall
    c = subprocess.Popen(z.split(" "), stdout = subprocess.PIPE, stderr = subprocess.PIPE)
  File "/usr/lib/python2.7/subprocess.py", line 394, in __init__
    errread, errwrite)
  File "/usr/lib/python2.7/subprocess.py", line 1047, in _execute_child
    raise child_exception
OSError: [Errno 2] No such file or directory

Exception in thread Thread-2:
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 801, in __bootstrap_inner
    self.run()
  File "/root/Desktop/tools/SMBetray/lib/ebcLib.py", line 391, in run
    self.listen()
  File "/root/Desktop/tools/SMBetray/lib/ebcLib.py", line 289, in listen
    self.openFirewall()
  File "/root/Desktop/tools/SMBetray/lib/ebcLib.py", line 208, in openFirewall
    c = subprocess.Popen(z.split(" "), stdout = subprocess.PIPE, stderr = subprocess.PIPE)
  File "/usr/lib/python2.7/subprocess.py", line 394, in __init__
    errread, errwrite)
  File "/usr/lib/python2.7/subprocess.py", line 1047, in _execute_child
    raise child_exception
OSError: [Errno 2] No such file or directory

Exception in thread Thread-4:
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 801, in __bootstrap_inner
    self.run()
  File "/root/Desktop/tools/SMBetray/lib/ebcLib.py", line 391, in run
    self.listen()
  File "/root/Desktop/tools/SMBetray/lib/ebcLib.py", line 289, in listen
    self.openFirewall()
  File "/root/Desktop/tools/SMBetray/lib/ebcLib.py", line 208, in openFirewall
    c = subprocess.Popen(z.split(" "), stdout = subprocess.PIPE, stderr = subprocess.PIPE)
  File "/usr/lib/python2.7/subprocess.py", line 394, in __init__
    errread, errwrite)
  File "/usr/lib/python2.7/subprocess.py", line 1047, in _execute_child
    raise child_exception
OSError: [Errno 2] No such file or directory

**Comment by tomeradi** [comment]
`apt install conntrack` solved it for me

**Comment by jordan12121** [comment]
I fix not installed python-nfqueue
